Django_axf/Django_axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('axf.urls',namespace='axf'))
]

Django_axf/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    url(r'^$',views.home,name='home'),
    url(r'^home/$',views.home,name='home'),

    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),

    url(r'^cart/$',views.cart,name='cart'),

    url(r'^mine/$',views.mine,name='mine'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^checkemail/$',views.checkemail,name='checkemail'),#ajax请求 数据交互
    url(r'^upfile/$',views.upfile,name='upfile'),#换头像

    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^subcart/$',views.subcart,name='subcart'),
    #ajax 请求
    url(r'^changecartselect/$',views.changecartselect,name='changecartselect'),
    url(r'^changecartall/$',views.changecartall,name='changecartall'),

    #订单生成与查询路由
    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>\d+)/$', views.orderdetail, name='orderdetail'),  # 订单详情


]

Django_axf/templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    闪购超市
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}








{% block content %}
    <div class="market">
        <div class="type-slider">
            <ul>
                {% for foodtype in foodtypes %}

                    <li>
                        <span></span>
                        {% if forloop.counter == foodtype.typesort %}
                            <a href="{% url 'axf:marketbase' %}">
                                {{ foodtype.typename }}
                            </a>

                        {% endif %}

                    </li>

                {% endfor %}
            </ul>
        </div>

        <nav>
            <ul>
                <li>
                    <span id="category-bt">
                        全部类型
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </span>
                </li>
                <li>
                    <span id="sort-bt">
                        综合排序
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </span>
                </li>
            </ul>
        </nav>

        {#主体商品列表#}
        <div class="main-content">
            <div class="content-wrapper">
                <ul>
                    {% for goods in goods_list %}

                        <li>
                            <a href="#">
                                <img class="goods-img" src="{{ goods.productimg }}" alt="">
                                <div class="goods-info">
                                    <p class="name">{{ goods.productlongname }}</p>
                                    <p class="detailtag">
                                        {% if goods.isxf %}
                                            <span class="xf">精选</span>
                                        {% endif %}
                                        <span>销量：{{ goods.productnum }}</span>
                                    </p>


                                    <p class="specifics">{{ goods.specifics }}</p>
                                    <p class="price">
                                        <span class="now-price">{{ goods.marketprice }}</span>
                                        <span class="market-price">{{ goods.marketprice }}</span>
                                    </p>
                                </div>
                            </a>

                            <div class="bt-wrapper">
                                <span class="glyphicon glyphicon-minus" data-goodsid="{{ goods.id }}"></span>
                                <i class="num">
                                    {% for cart in carts %}
                                        {% if cart.goods.id == goods.id %}
                                            {{ cart.goodsnumber }}
                                        {% endif %}
                                    {% endfor %}

                                </i>
                                <span class="glyphicon glyphicon-plus" data-goodsid="{{ goods.id }}" ></span>
                            </div>
                        </li>

                    {% endfor %}
                </ul>
            </div>

            <div class="bounce-view category-view">
                <div class="bounce-wrapper">
                    {% for childtype in childtype_list %}
                        <a href="{% url 'axf:market' childtype.id 0%}">{{ childtype.name }}</a>
                    {% endfor %}

                    
                </div>
            </div>
            <div class="bounce-view sort-view">
                <div class="bounce-wrapper">
                    <a href="{% url 'axf:market' childid 0%}">综合排序</a>
                    <a href="{% url 'axf:market' childid 1%}">销量排序</a>
                    <a href="{% url 'axf:market' childid 2%}">价格最高</a>
                    <a href="{% url 'axf:market' childid 3%}">价格最低</a>
                </div>
            </div>

        </div>


    </div>
{% endblock %}