Django_axf/Django_axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('axf.urls',namespace='axf'))
]

Django_axf/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    url(r'^$',views.home,name='home'),
    url(r'^home/$',views.home,name='home'),

    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),

    url(r'^cart/$',views.cart,name='cart'),

    url(r'^mine/$',views.mine,name='mine'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^checkemail/$',views.checkemail,name='checkemail'),#ajax请求 数据交互
    url(r'^upfile/$',views.upfile,name='upfile'),#换头像

    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^subcart/$',views.subcart,name='subcart'),
    #ajax 请求
    url(r'^changecartselect/$',views.changecartselect,name='changecartselect'),
    url(r'^changecartall/$',views.changecartall,name='changecartall'),

    #订单生成与查询路由
    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>\d+)/$', views.orderdetail, name='orderdetail'),  # 订单详情


]

Django_axf/templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}



{% block content %}
    <div class="login">
        <div class="back">
            <a href="{% url 'axf:mine' %}"><i class="glyphicon glyphicon-circle-arrow-left"></i></a>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="input-group input-group-lg" id="email">
                <span class="input-group-addon" id="sizing-addon2">邮箱</span>
                <input type="text" class="form-control" placeholder="请输入邮箱" name="email">
            </div>
            <div class="input-group input-group-lg" id="password">
                <span class="input-group-addon" id="sizing-addon2">密码</span>
                <input type="password" class="form-control" placeholder="请输入密码" name="password">
            </div>
            <div class="input-group input-group-lg" style="color: red">{{ err }}</div>
            <div class="input-group input-group-lg" style="color: red">{{ err1 }}</div>

            <div class="input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon2">验证码</span>
                <input type="text" class="form-control" placeholder="请输入图片中验证码" name="verifycode">
                <img src="{% static 'mine/img/vc.png' %}" alt="">
            </div>
            <input type="submit" id="subButton" value="登录">
        </form>
    </div>
{% endblock %}

Django_axf/templates/mine/logout.html
{% extends 'base/base.html' %}
{% load static %}

Django_axf/templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}
{% load static %}

{% block title %}
    我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <a href="{% url 'axf:upfile' %}">
                    <img src="/static/upfile/{{ user.img | default:'touxiang.jpg' }}" alt="">
                </a>
            </div>
            <div class="user-content">
                <p><a id="login_ck"><i
                        class="glyphicon glyphicon-user" ></i> {{ user.name | default:'未登录' }}</a></p>
                <p><i class="glyphicon glyphicon-stats"></i> 等级{{ user.rank | default:'无' }}</p>

                <a href="{% url 'axf:register' %}"><span class="register">注册</span></a>

            </div>
        </div>

        <div class="collect">
            <span> <i class="glyphicon glyphicon-heart"></i> 商品收藏</span>
        </div>
        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="{% url 'axf:orderlist' %}">查看全部订单 <i class="glyphicon glyphicon-chevron-right"></i></a>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-usd">
                                    <span class="badge">{% if waitpay %}
                                        {{ waitpay }}
                                    {% endif %}</span>
                                </dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-envelope">
                                    <span class="badge">{% if paydone %}
                                        {{ paydone }}
                                    {% endif %}</span>
                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><i class="glyphicon glyphicon-pencil"></i></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><i class="glyphicon glyphicon-retweet"></i></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>
            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><i class="glyphicon glyphicon-credit-card"></i></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><i class="glyphicon glyphicon-import"></i></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><i class="glyphicon glyphicon-phone-alt"></i></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><i class="glyphicon glyphicon-asterisk"></i></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>
            {% if user.name %}
                <section class="quit">
                    <a href="{% url 'axf:logout' %}">退出登录</a>
                </section>
            {% endif %}
        </div>


    </div>
{% endblock %}

Django_axf/templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}


{% block title %}
    注册
{% endblock %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/registe.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/register.js' %}"></script>
{% endblock %}


{% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'axf:mine' %}"><i class="glyphicon glyphicon-circle-arrow-left"></i></a>
        </div>

        <form action="{% url 'axf:register' %}" method="post">
            {% csrf_token %}


{#                <div class="form-group has-success has-feedback">#}
{#                 <label class="control-label" for="inputSuccess2">Input with success</label>#}
{#                 <input type="text" class="form-control" id="inputSuccess2" aria-describedby="inputSuccess2Status">#}
{#                 <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>#}
{#                 <span id="inputSuccess2Status" class="sr-only">(success)</span>#}
{#                </div>#}

{#                <div class="form-group has-error has-feedback">#}
{#                 <label class="control-label" for="inputError2">Input with error</label>#}
{#                 <input type="text" class="form-control" id="inputError2" aria-describedby="inputError2Status">#}
{#                 <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>#}
{#                 <span id="inputError2Status" class="sr-only">(error)</span>#}
{#                </div>#}


            <div class="input-group input-group-lg" id="email">
                <span class="input-group-addon" >邮箱</span>
                <input type="text" class="form-control" placeholder="请输入邮箱" name="email" data-toggle="popover" data-placement="bottom" >
                <span -class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
{#                glyphicon glyphicon-remove glyphicon glyphicon-ok#}
            </div>

            <div class="input-group input-group-lg" id="password">
                <span class="input-group-addon" id="sizing-addon2">密码</span>
                <input type="password" class="form-control" placeholder="6~12个字符" name="password" data-toggle="popover" data-placement="bottom">
                <span -class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
            </div>
            <div class="input-group input-group-lg" id="name">
                <span class="input-group-addon" id="sizing-addon2">昵称</span>
                <input type="text" class="form-control" placeholder="6~12个字符" name="name" data-placement="bottom" data-toggle="popover">
                <span -class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
            </div>
            <div class="input-group input-group-lg" id="verifycode">
                <span class="input-group-addon" id="sizing-addon2">验证码</span>
                <input type="text" class="form-control" placeholder="请输入图片中验证码" name="verifycode" data-placement="bottom" data-toggle="popover">
                <span -class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                <img src="{% static 'mine/img/vc.png' %}" alt="">
            </div>

{#            <input type="submit" id="subButton" value="注册">#}

        </form>
        <button id="subButton">注册</button>



    </div>
{% endblock %}

Django_axf/templates/mine/upfile.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    上传头像
{% endblock %}

{% block content %}
    <div class="back">
            <a href="{% url 'axf:mine' %}"><i class="glyphicon glyphicon-circle-arrow-left"></i></a>
    </div>
    <div class="upfile">
        <form action="{% url 'axf:upfile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" value="上传文件" name="file">
            <input type="submit" value="上传">
        </form>
    </div>
{% endblock %}