Django_axf/Django_axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('axf.urls',namespace='axf'))
]

Django_axf/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    url(r'^$',views.home,name='home'),
    url(r'^home/$',views.home,name='home'),

    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),

    url(r'^cart/$',views.cart,name='cart'),

    url(r'^mine/$',views.mine,name='mine'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^checkemail/$',views.checkemail,name='checkemail'),#ajax请求 数据交互
    url(r'^upfile/$',views.upfile,name='upfile'),#换头像

    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^subcart/$',views.subcart,name='subcart'),
    #ajax 请求
    url(r'^changecartselect/$',views.changecartselect,name='changecartselect'),
    url(r'^changecartall/$',views.changecartall,name='changecartall'),

    #订单生成与查询路由
    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>\d+)/$', views.orderdetail, name='orderdetail'),  # 订单详情


]

Django_axf/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.1/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">


    {% block extcss %}
    {% endblock %}
</head>
<body>
{% block body %}

    {# 导航#}
    {% block header %}
        <header>罗哥超市</header>
    {% endblock %}


    {# 主体内容#}
    <div class="hidescroll">
        <div id="content">
            {% block content %}
                主体内容
            {% endblock %}
        </div>
    </div>

    {# 尾部#}
    {% block footer %}
        <footer>
            <a href="{% url 'axf:home' %}" class="home">
                <dl>
                    <dt><span></span></dt>
                    <dd>首页</dd>
                </dl>
            </a>

            <a href="{% url 'axf:marketbase' %}" class="market">
                <dl>
                    <dt><span></span></dt>
                    <dd>超市闪购</dd>
                </dl>
            </a>


            <a href="{% url 'axf:cart' %}" class="cart">
                <dl>
                    <dt><span></span></dt>
                    <dd>购物车</dd>
                </dl>
            </a>


            <a href="{% url 'axf:mine' %}" class="mine">
                <dl>
                    <dt><span></span></dt>
                    <dd>我的</dd>
                </dl>
            </a>

        </footer>
    {% endblock %}

{% endblock %}

<script src="{% static 'base/js/jquery.min.js' %}"></script>
<script src="https://cdn.bootcss.com/jquery-cookie/1.3.1/jquery.cookie.js"></script>

<script src="https://cdn.bootcss.com/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>

<script src="{% static 'base/js/base.js' %}"></script>

{% block extjs %}

{% endblock %}
</body>
</html>