Django_axf/Django_axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('axf.urls',namespace='axf'))
]

Django_axf/axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    url(r'^$',views.home,name='home'),
    url(r'^home/$',views.home,name='home'),

    url(r'^market/$',views.market,name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$',views.market,name='market'),

    url(r'^cart/$',views.cart,name='cart'),

    url(r'^mine/$',views.mine,name='mine'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^checkemail/$',views.checkemail,name='checkemail'),#ajax请求 数据交互
    url(r'^upfile/$',views.upfile,name='upfile'),#换头像

    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^subcart/$',views.subcart,name='subcart'),
    #ajax 请求
    url(r'^changecartselect/$',views.changecartselect,name='changecartselect'),
    url(r'^changecartall/$',views.changecartall,name='changecartall'),

    #订单生成与查询路由
    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>\d+)/$', views.orderdetail, name='orderdetail'),  # 订单详情


]

Django_axf/templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    购物车
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="cart">
        <ul>
            {% for cart in carts %}
                <li>
                    <div class="confirm-wrapper" data-cartid="{{ cart.id }}">
                        {% if cart.isselect %}
                            <span class="glyphicon glyphicon-ok"></span>
                        {% else %}
                            <span class="no"></span>
                        {% endif %}
                    </div>
                    <div class="content-wrapper">
                        <div class="img">
                            <img src="{{ cart.goods.productimg }}" alt="">
                        </div>
                        <div class="detail">
                            <p class="name">{{ cart.goods.productlongname }}</p>
                            <p class="price" price="{{ cart.goods.price }}">{{ cart.goods.price }}</p>
                            <p class="num" goodsnumber="{{ cart.goodsnumber }}">×{{ cart.goodsnumber }}</p>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>

        <div class="bill">

            <div class="bill-left">
                <div class="all" isall="{{ isall }}">
                    {% if isall %}
                        <span class="glyphicon glyphicon-ok"></span>
                    {% else %}
                        <span class="no"></span>
                    {% endif %}
                    <b>全选</b>
                </div>
                <div class="total">
                    <span>￥</span>
                    <b></b>
                </div>
            </div>
            <div class="bill-right">
                <a href="{% url 'axf:generateorder' %}">下单</a>
            </div>
        </div>

    </div>
{% endblock %}

Django_axf/templates/cart/no-login.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    登录页面
{% endblock %}

{% block content %}
    登录
{% endblock %}